### ISSUE TITLE
USER STORY: Add comment in poll section on homepage

### ISSUE THREAD

**Issue by AnnickRynne** [AnnickRynne/love-running#2]
In order to **add a comment** as a **user**, I can **select a 'comment' option on the homepage inside the new pool feature**

## **Acceptance Criteria:**
- Acceptance Criteria 1: User can enter up to 150 characters
- Acceptance Criteria 2: Arial Font size 12

## **Tasks:**
- [x] Create comment window using html input
- [ ] Limit to 150 characters
- [ ] Pop up message when user is over 150 characters
